// <auto-generated />
using System;
using ContasPagar.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContasPagar.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251001191706_CriacaoTabelaContasPagar")]
    partial class CriacaoTabelaContasPagar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ContasPagar.Api.Domain.Entities.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("PercentualJurosDiaAplicado")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("PercentualMultaAplicado")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("QuantidadeDiasAtraso")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("contas_pagar");
                });
#pragma warning restore 612, 618
        }
    }
}
